#### general settings
name: cfsrcnn_x4
use_tb_logger: false
model: sr
distortion: sr
scale: 4
gpu_ids: [0]

#### network structures
network_G:
  which_model_G: cfsrcnn
  scale: 4

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT_rcan
    dataroot_GT: /home/data/disk2/wsq/Datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_LQ: /home/data/disk2/wsq/Datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    # dataroot_GT: dataset/DIV2K_scale_sub/GT
    # dataroot_LQ: dataset/DIV2K_scale_sub/LR

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: urban100
    mode: LQGT_rcan
    dataroot_GT: /home/data/disk2/wsq/Datasets/benchmark/Set5/HR
    dataroot_LQ: /home/data/disk2/wsq/Datasets/benchmark/Set5/LR_bicubic/X3
    # dataroot_GT: dataset/DIV2K_valid_sub/GT
    # dataroot_LQ: dataset/DIV2K_valid_sub/LR

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.999
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [1000000]
  restarts: [1000000]
  restart_weights: [1]
  eta_min: !!float 1e-7
  lr_gamma: 0.5
  clear_state: 1000000

  pixel_criterion: l2
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: 5000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
